version: 2.1

orbs:
  node: circleci/node@6
  python: circleci/python@2

workflows:
  pack-qt-libs:
    jobs:
      - build

jobs:
  build:
    executor: linux
    resource_class: arm.medium
    steps:
      - checkout
      - node/install:
          node-version: 22.9.0
          install-yarn: false
      - node/install-packages:
          pkg-manager: npm
      - run: python -m pip install --upgrade pip setuptools
      - run: python -m pip install aqtinstall
      #   python -m pip install pyqt5-sip
      #   python -m pip install pyqt5 --config-settings --confirm-license= --verbose
      #   python -m pip install "anki == 24.06.3"
      #   python -m pip install "aqt == 24.6.3"
      #   python -m pip install "aqt == 24.6.3"
      - run: aqt install-qt --outputdir ~/Qt linux_arm64 desktop 6.8.0 linux_gcc_arm64
      - run: echo LSLSLSLSLLSLSLSLSLSLLS
      - run: ls ~
      - run: echo LSLSLSLSLLSLSLSLSLSLLS 222222222222222222
      - run: ls ~/Qt
      - run: RELEASE_VERSION=`node -p "'version='+require('./package').version"`
      - run: echo $RELEASE_VERSION
      - run: chmod +x src/qt-mkdir.sh
      - run: src/qt-mkdir.sh ~/qt_tmp
      - run: chmod +x src/qt-copy-linux.sh
      - run: src/qt-copy-linux.sh ~/qt_tmp ~/Qt/gcc_arm64
      - run: cd ~/qt_tmp
      - run: tar -czf ../aarch64.gz *
