version: 2.1

workflows:
  pack-qt:
    jobs:
      - pack-qt

jobs:
  pack-qt:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: python -m pip install --upgrade setuptools
      - run: python -m pip install aqtinstall
      - run: python -m aqt install-qt --outputdir ~/Qt linux_arm64 desktop 6.8.0 linux_gcc_arm64
      - run: echo LSLSLSLSLLSLSLSLSLSLLS
      - run: ls ~
      - run: echo LSLSLSLSLLSLSLSLSLSLLS 222222222222222222
      - run: ls ~/Qt
      - run: RELEASE_VERSION=`node -p "'version='+require('./package').version"`
      - run: echo $RELEASE_VERSION
      - run: chmod +x src/qt-mkdir.sh
      - run: src/qt-mkdir.sh ~/qt_tmp
      - run: chmod +x src/qt-copy-linux.sh
      - run: src/qt-copy-linux.sh ~/qt_tmp ~/Qt/gcc_arm64
      - run: cd ~/qt_tmp
      - run: tar -czf ../aarch64.gz *
      - run: echo LSLSLSLSLLSLSLSLSLSLLS
      - run: ls ~
