# $1 is tmp path - ${{ github.workspace }}/../__tmp

rm -rf $1
mkdir -p $1

mkdir -p $1/plugins
mkdir -p $1/plugins/platforms
mkdir -p $1/plugins/qmltooling

mkdir -p $1/qml
mkdir -p $1/qml/QtTest
mkdir -p $1/qml/QtQuick
mkdir -p $1/qml/QtQuick/Window
mkdir -p $1/qml/QtQuick/VectorImage
mkdir -p $1/qml/QtQuick/tooling
mkdir -p $1/qml/QtQuick/Templates
mkdir -p $1/qml/QtQuick/Shapes
mkdir -p $1/qml/QtQuick/Particles
mkdir -p $1/qml/QtQuick/NativeStyle
mkdir -p $1/qml/QtQuick/NativeStyle/util
mkdir -p $1/qml/QtQuick/NativeStyle/controls
mkdir -p $1/qml/QtQuick/LocalStorage
mkdir -p $1/qml/QtQuick/Layouts
mkdir -p $1/qml/QtQuick/Effects
mkdir -p $1/qml/QtQuick/Dialogs
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Universal
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Material
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Imagine
mkdir -p $1/qml/QtQuick/Dialogs/quickimpl/qml/+Fusion
mkdir -p $1/qml/QtQuick/Controls
mkdir -p $1/qml/QtQuick/Controls/Universal
mkdir -p $1/qml/QtQuick/Controls/Universal/impl
mkdir -p $1/qml/QtQuick/Controls/Material
mkdir -p $1/qml/QtQuick/Controls/Material/impl
mkdir -p $1/qml/QtQuick/Controls/impl
mkdir -p $1/qml/QtQuick/Controls/Imagine
mkdir -p $1/qml/QtQuick/Controls/Imagine/impl
mkdir -p $1/qml/QtQuick/Controls/Fusion
mkdir -p $1/qml/QtQuick/Controls/Fusion/impl
mkdir -p $1/qml/QtQuick/Controls/Basic
mkdir -p $1/qml/QtQuick/Controls/Basic/impl
mkdir -p $1/qml/QtQml
mkdir -p $1/qml/QtQml/XmlListModel
mkdir -p $1/qml/QtQml/WorkerScript
mkdir -p $1/qml/QtQml/Models
mkdir -p $1/qml/QtNetwork
mkdir -p $1/qml/QtCore
mkdir -p $1/qml/Qt
mkdir -p $1/qml/Qt/test
mkdir -p $1/qml/Qt/test/controls
mkdir -p $1/qml/Qt/labs
mkdir -p $1/qml/Qt/labs/wavefrontmesh
mkdir -p $1/qml/Qt/labs/sharedimage
mkdir -p $1/qml/Qt/labs/settings
mkdir -p $1/qml/Qt/labs/qmlmodels
mkdir -p $1/qml/Qt/labs/platform
mkdir -p $1/qml/Qt/labs/folderlistmodel
mkdir -p $1/qml/Qt/labs/animation
mkdir -p $1/qml/QmlTime
mkdir -p $1/qml/QML
mkdir -p $1/qml/Assets
mkdir -p $1/qml/Assets/Downloader
